name: car_maintenance_app
description: Egy egyszerű autókarbantartó alkalmazás Flutterben.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # === EZ AZ ÚJ, HIÁNYZÓ BLOKK A MAGYAROSÍTÁSHOZ ===
  flutter_localizations:
    sdk: flutter
  # ===============================================

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2 # Frissítettem egy stabilabb verzióra
  intl: ^0.20.2
  http: ^1.2.1
  dropdown_search: ^5.0.6
  diacritic: ^0.1.5
  pdf: ^3.10.8
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  image_picker: ^1.1.2
  csv: ^6.0.0
  file_picker: ^8.0.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
